name: Build and publish
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build main branch
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: '18'
      - run: yarn install
      - run: yarn test
      - run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
