name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    if: ${{ github.event_name != 'pull_request' }}
    name: Test on main for node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn test
  pr:
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn install
      - run: yarn test
